[project]
name = "thermalbar"
version = "0.1.0"
description = "Project Simulation and Optimisation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "adjusttext>=1.3.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "scipy>=1.17.0",
]
